on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send repo to Dataverse 
        uses: IQSS/dataverse-uploader@v1.4
        with:
          DATAVERSE_TOKEN: 34b39e50-9035-4523-90ee-a7a37ca546bc
          DATAVERSE_SERVER: https://dataverse.tdl.org
          DATAVERSE_DATASET_DOI: doi:10.18738/T8/UO4F9F
          DELETE: True
          PUBLISH: True
